### PR TITLE
Auto Generate Custom URLs

### LINKED ISSUE #5: Add auto short code generator, rather than always entering custom URLs
**Is your feature request related to a problem? Please describe.**
Whenever a new link needs to be created, A custom URL has to be added which is not ideal

**Describe the solution you'd like**
Whenever custom url is left empty auto-generate a non-colliding 5-10 character code as a custom url

### PR DESCRIPTION
**Pull request by luckykumarirai**
### What is the current behavior?
 Every time needs to enter a custom URL.

### What is the new behavior?
Whenever we do not want to enter a custom URL by click on the button auto-generate 5-10 character code as a custom URL.
if we think need to give our own custom URL then we can enter both functionality present.

### Review link:
https://fireshort-e4651.web.app/admin

email:- shorturl@gmail.com
Password:- Url@123

close #5

### CODE REVIEW

**Comment by ashuvssut** [comment]
hello! please provide new test 'authentication credentials' from firebase to test your changes.

**Comment by xprilion** [comment]
@luckykumarirai thanks for the PR! I have tested that while creating new links its easy to generate random characters, however I am unable to change the same when editing the links already created. Please fix.

**Review by xprilion — CHANGES_REQUESTED** [review]
Fix generating random characters when editing links

**Comment by luckykumarirai** [comment]
Now I have fixed generating random characters when editing links problem.

**Review by xprilion — APPROVED** [review]

**Pull request merged**
